import React, { useState, useRef, useEffect } from 'react';
import { Send } from 'lucide-react';

export const ChatInput = ({ onSendMessage, disabled }) => {
  const [text, setText] = useState('');
  const textareaRef = useRef(null);

  const adjustTextareaHeight = () => {
    if (textareaRef.current) {
      textareaRef.current.style.height = 'auto';
      textareaRef.current.style.height = `${Math.min(textareaRef.current.scrollHeight, 150)}px`;
    }
  };

  useEffect(() => {
    adjustTextareaHeight();
  }, [text]);

  const handleSubmit = () => {
    if (text.trim() && !disabled) {
      onSendMessage(text.trim());
      setText('');
      if (textareaRef.current) textareaRef.current.style.height = 'auto';
    }
  };

  const handleKeyDown = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSubmit();
    }
  };

  return (
    <div className="w-full flex flex-col space-y-2 pb-2 max-w-4xl mx-auto">
      
      {/* Main Input Area */}
      <div className="relative group flex items-end">
        <textarea
          ref={textareaRef}
          value={text}
          onChange={(e) => setText(e.target.value)}
          onKeyDown={handleKeyDown}
          placeholder="Ask O.N.E. for help with code, architecture, or deployments..."
          disabled={disabled}
          className="block w-full pl-4 pr-12 py-3.5 bg-white border border-stone-300 rounded-md focus:border-stone-900 focus:ring-0 transition-colors text-sm font-medium text-stone-900 resize-none shadow-sm placeholder:text-stone-400"
          rows={1}
        />
        <div className="absolute right-2.5 bottom-2.5 flex items-center gap-2">
          <button
            onClick={handleSubmit}
            disabled={disabled || !text.trim()}
            className="h-8 w-8 bg-stone-900 hover:bg-stone-800 text-white rounded-sm flex items-center justify-center transition-colors disabled:opacity-30 disabled:cursor-not-allowed"
          >
            <Send size={14} className="ml-0.5" />
          </button>
        </div>
      </div>
      
      <p className="text-center text-[10px] text-stone-400 font-mono tracking-widest uppercase pt-1">
         Data generated by AI may be inaccurate. Verification recommended.
      </p>
    </div>
  );
};
