import React, { useState, useRef, useEffect } from 'react';
import { Send } from 'lucide-react';

export const ChatInput = ({ onSendMessage, disabled }) => {
  const [text, setText] = useState('');
  const textareaRef = useRef(null);

  const adjustTextareaHeight = () => {
    if (textareaRef.current) {
      textareaRef.current.style.height = 'auto';
      textareaRef.current.style.height = `${Math.min(textareaRef.current.scrollHeight, 150)}px`;
    }
  };

  useEffect(() => {
    adjustTextareaHeight();
  }, [text]);

  const handleSubmit = () => {
    if (text.trim() && !disabled) {
      onSendMessage(text.trim());
      setText('');
      if (textareaRef.current) textareaRef.current.style.height = 'auto';
    }
  };

  const handleKeyDown = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSubmit();
    }
  };

  return (
    <div className="w-full flex flex-col space-y-2 pb-2 max-w-4xl mx-auto">
      
      {/* Main Input Area */}
      <div className="relative group flex items-end">
        <textarea
          ref={textareaRef}
          value={text}
          onChange={(e) => setText(e.target.value)}
          onKeyDown={handleKeyDown}
          placeholder="Ask O.N.E. for help with code, architecture, or deployments..."
          disabled={disabled}
          className="block w-full pl-5 pr-14 py-4 bg-white/5 border border-white/10 rounded-2xl focus:ring-1 focus:ring-[#4c6ef5]/30 focus:border-[#4c6ef5]/50 transition-all text-sm font-medium text-white resize-none shadow-xl shadow-black/10 placeholder:text-slate-500"
          rows={1}
        />
        <div className="absolute right-2 bottom-2 flex items-center gap-2">
          <button
            onClick={handleSubmit}
            disabled={disabled || !text.trim()}
            className="h-9 w-9 bg-[#4c6ef5] hover:bg-[#4c6ef5]/90 text-white rounded-xl flex items-center justify-center shadow-lg shadow-[#4c6ef5]/30 transition-all disabled:opacity-50 disabled:cursor-not-allowed transform active:scale-95"
          >
            <Send size={16} className="ml-1" />
          </button>
        </div>
      </div>
      
      <p className="text-center text-[10px] text-slate-500 font-semibold tracking-wide uppercase pt-2">
         Data generated by AI may be inaccurate. Verification recommended.
      </p>
    </div>
  );
};
