import React, { useState, useRef, useEffect } from 'react';
import { useChecklist } from '../context/ChecklistContext';
import { Send, CheckCircle2, HelpCircle, SkipForward } from 'lucide-react';

export const ChatInput = ({ onSendMessage, disabled }) => {
  const [text, setText] = useState('');
  const textareaRef = useRef(null);
  const { markCurrentTaskDone, loading: isActionLoading } = useChecklist();

  const adjustTextareaHeight = () => {
    if (textareaRef.current) {
      textareaRef.current.style.height = 'auto';
      textareaRef.current.style.height = `${Math.min(textareaRef.current.scrollHeight, 150)}px`;
    }
  };

  useEffect(() => {
    adjustTextareaHeight();
  }, [text]);

  const handleSubmit = () => {
    if (text.trim() && !disabled) {
      onSendMessage(text.trim());
      setText('');
      if (textareaRef.current) textareaRef.current.style.height = 'auto';
    }
  };

  const handleKeyDown = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSubmit();
    }
  };

  const quickActions = [
    { label: 'Mark as done', action: markCurrentTaskDone, icon: CheckCircle2 },
    { label: 'Ask for help', fill: 'Can you explain this in more detail?', icon: HelpCircle },
    { label: 'Skip this', fill: 'Can I skip this task?', icon: SkipForward }
  ];

  const handleQuickAction = (actionLabel, action, fillContent) => {
    if (disabled || isActionLoading) return;
    
    if (actionLabel === 'Ask for help' || actionLabel === 'Skip this') {
      if (fillContent) onSendMessage(fillContent);
      return;
    }

    if (action) {
      action();
    } else if (fillContent) {
      setText(fillContent);
      if (textareaRef.current) textareaRef.current.focus();
    }
  };

  return (
    <div className="w-full flex flex-col space-y-3 pb-2 max-w-4xl mx-auto">
      
      {/* Quick Actions (Stitch Style Pills) */}
      <div className="flex flex-wrap gap-2">
        {quickActions.map((action, idx) => {
          const Icon = action.icon;
          return (
            <button
              key={idx}
              onClick={() => handleQuickAction(action.label, action.action, action.fill)}
              className="flex-none flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-white/5 text-slate-400 hover:text-white border border-white/10 hover:border-[#4c6ef5]/30 hover:bg-white/10 text-[11px] font-bold transition-all shadow-sm disabled:opacity-50 disabled:cursor-not-allowed"
              disabled={disabled || isActionLoading}
            >
              <Icon size={12} className={action.label === 'Mark as done' ? 'text-emerald-400' : ''} />
              {action.label}
            </button>
          )
        })}
      </div>
      
      {/* Main Input Area */}
      <div className="relative group flex items-end">
        <textarea
          ref={textareaRef}
          value={text}
          onChange={(e) => setText(e.target.value)}
          onKeyDown={handleKeyDown}
          placeholder="Ask O.N.E. for help with code, architecture, or deployments..."
          disabled={disabled}
          className="block w-full pl-5 pr-14 py-4 bg-white/5 border border-white/10 rounded-2xl focus:ring-1 focus:ring-[#4c6ef5]/30 focus:border-[#4c6ef5]/50 transition-all text-sm font-medium text-white resize-none shadow-xl shadow-black/10 placeholder:text-slate-500"
          rows={1}
        />
        <div className="absolute right-2 bottom-2 flex items-center gap-2">
          <button
            onClick={handleSubmit}
            disabled={disabled || !text.trim()}
            className="h-9 w-9 bg-[#4c6ef5] hover:bg-[#4c6ef5]/90 text-white rounded-xl flex items-center justify-center shadow-lg shadow-[#4c6ef5]/30 transition-all disabled:opacity-50 disabled:cursor-not-allowed transform active:scale-95"
          >
            <Send size={16} className="ml-1" />
          </button>
        </div>
      </div>
      
      <p className="text-center text-[10px] text-slate-500 font-semibold tracking-wide uppercase pt-2">
         Data generated by AI may be inaccurate. Verification recommended.
      </p>
    </div>
  );
};
