"""Add role_tasks table

Revision ID: 18322371e981
Revises: e67135235015
Create Date: 2026-08-13 23:10:20.426907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18322371e981'
down_revision: Union[str, Sequence[str], None] = 'e67135235015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department_role', sa.String(length=100), nullable=False),
    sa.Column('tasks', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_tasks_department_role'), 'role_tasks', ['department_role'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_tasks_department_role'), table_name='role_tasks')
    op.drop_table('role_tasks')
    # ### end Alembic commands ###
