"""add_chat_history_jsonb_to_sessions

Revision ID: abc8607b22d7
Revises: 5bf920f9294b
Create Date: 2026-04-15 11:04:05.766839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abc8607b22d7'
down_revision: Union[str, Sequence[str], None] = '5bf920f9294b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding_sessions', sa.Column('chat_history', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onboarding_sessions', 'chat_history')
    # ### end Alembic commands ###
