"""Add progress_percentage

Revision ID: ce1ab745b6d9
Revises: abc8607b22d7
Create Date: 2026-06-15 21:17:40.021690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce1ab745b6d9'
down_revision: Union[str, Sequence[str], None] = 'abc8607b22d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding_sessions', sa.Column('progress_percentage', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onboarding_sessions', 'progress_percentage')
    # ### end Alembic commands ###
