"""Add role and task tracking columns

Revision ID: e67135235015
Revises: ce1ab745b6d9
Create Date: 2026-08-13 22:57:01.739544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e67135235015'
down_revision: Union[str, Sequence[str], None] = 'ce1ab745b6d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department_role', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('tasks_completed', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('onboarding_progress', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_progress')
    op.drop_column('users', 'tasks_completed')
    op.drop_column('users', 'department_role')
    # ### end Alembic commands ###
