import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { Link } from 'react-router-dom';
import { 
  BarChart, Bar, AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
  PieChart, Pie, Cell, ScatterChart, Scatter, ZAxis,
  Radar, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis
} from 'recharts';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { 
  Search, Bell, Plus, LayoutDashboard, Users, BarChart2, MessageSquare, Settings, User as UserIcon, AlertTriangle,
  Download, Loader2
} from 'lucide-react';

export const AdminAnalyticsPage = () => {
    const [data, setData] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);
    const [isExporting, setIsExporting] = useState(false);
    const [adminProfile, setAdminProfile] = useState(null);

    useEffect(() => {
        const fetchAdminProfile = async () => {
            try {
                const token = sessionStorage.getItem('token');
                const res = await axios.get('http://localhost:8000/api/v1/admin/profile', {
                    headers: { Authorization: `Bearer ${token}` },
                    withCredentials: true,
                });
                setAdminProfile(res.data);
            } catch (err) {
                console.error('Failed to load admin profile', err);
            }
        };
        fetchAdminProfile();
    }, []);

    const handleExportPDF = async () => {
        if (!data || isExporting) return;
        setIsExporting(true);
        try {
            const doc = new jsPDF();
            const pageWidth = doc.internal.pageSize.getWidth();
            const margin = 14;
            let cursorY = 20;

            // ── A. Document Title & Timestamp ──────────────────────────
            doc.setFontSize(22);
            doc.setFont('helvetica', 'bold');
            doc.setTextColor(17, 24, 39);
            doc.text('O.N.E. Analytics Deep-Dive Report', margin, cursorY);
            cursorY += 8;

            doc.setFontSize(10);
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(107, 114, 128);
            doc.text(`Generated: ${new Date().toLocaleString()}`, margin, cursorY);
            cursorY += 4;

            // Thin divider line
            doc.setDrawColor(209, 213, 219);
            doc.setLineWidth(0.5);
            doc.line(margin, cursorY, pageWidth - margin, cursorY);
            cursorY += 8;

            // ── B. Meta Data Table ─────────────────────────────────────
            const completionMatrix = data?.quantitative?.completion_matrix || [];
            const avgCompletion = completionMatrix.length > 0
                ? (completionMatrix.reduce((sum, d) => sum + (d.percent_complete || 0), 0) / completionMatrix.length).toFixed(1)
                : 'N/A';

            autoTable(doc, {
                startY: cursorY,
                head: [['Field', 'Value']],
                body: [
                    ['Report Type', 'AI HR Diagnostics — Deep Dive'],
                    ['Generated By', 'O.N.E. Admin System'],
                    ['Total Developers Analyzed', String(completionMatrix.length)],
                    ['Overall Avg. Completion', `${avgCompletion}%`],
                ],
                theme: 'grid',
                headStyles: { fillColor: [79, 70, 229], textColor: 255, fontStyle: 'bold', fontSize: 9 },
                bodyStyles: { fontSize: 9, textColor: [31, 41, 55] },
                alternateRowStyles: { fillColor: [243, 244, 246] },
                margin: { left: margin, right: margin },
                tableWidth: 'auto',
            });
            cursorY = doc.lastAutoTable.finalY + 12;

            // ── C. Cohort Progress Table ───────────────────────────────
            doc.setFontSize(13);
            doc.setFont('helvetica', 'bold');
            doc.setTextColor(17, 24, 39);
            doc.text('Cohort Progress Tracker', margin, cursorY);
            cursorY += 6;

            autoTable(doc, {
                startY: cursorY,
                head: [['Developer', 'Completion %']],
                body: completionMatrix.map(d => [
                    d.employee_name || d.developer_id || '—',
                    `${d.percent_complete ?? 0}%`,
                ]),
                theme: 'striped',
                headStyles: { fillColor: [79, 70, 229], textColor: 255, fontStyle: 'bold', fontSize: 9 },
                bodyStyles: { fontSize: 9, textColor: [31, 41, 55] },
                alternateRowStyles: { fillColor: [238, 242, 255] },
                margin: { left: margin, right: margin },
            });
            cursorY = doc.lastAutoTable.finalY + 12;

            // ── D. AI Qualitative Insights Table ───────────────────────
            doc.setFontSize(13);
            doc.setFont('helvetica', 'bold');
            doc.setTextColor(17, 24, 39);
            doc.text('AI Qualitative Insights — Deep Diagnostics', margin, cursorY);
            cursorY += 6;

            const devInsights = data?.qualitative?.developer_insights || [];
            const sentimentIndex = data?.qualitative?.sentiment_index || [];
            const autonomyScores = data?.qualitative?.autonomy_scores || [];

            const qualRows = devInsights.map(insight => {
                const sentiment = sentimentIndex.find(s =>
                    s.developer_id === insight.developer_id || s.employee_name === insight.employee_name
                );
                const autonomy = autonomyScores.find(a =>
                    a.developer_id === insight.developer_id || a.employee_name === insight.employee_name
                );
                return {
                    name: insight.employee_name || insight.developer_id || '—',
                    complexity: insight.question_complexity_score ?? '—',
                    severity: insight.question_severity || '—',
                    autonomy: autonomy?.independence_rating ?? '—',
                    sentiment: sentiment?.primary_emotion || '—',
                    frustration: sentiment?.frustration_score ?? null,
                };
            });

            autoTable(doc, {
                startY: cursorY,
                head: [['Developer', 'Complexity (1-10)', 'Severity', 'Autonomy Score', 'Sentiment']],
                body: qualRows.map(r => [
                    r.name,
                    String(r.complexity),
                    r.severity,
                    String(r.autonomy),
                    r.sentiment,
                ]),
                theme: 'striped',
                headStyles: { fillColor: [79, 70, 229], textColor: 255, fontStyle: 'bold', fontSize: 8 },
                bodyStyles: { fontSize: 8, textColor: [31, 41, 55] },
                alternateRowStyles: { fillColor: [238, 242, 255] },
                margin: { left: margin, right: margin },
                didParseCell: (hookData) => {
                    // Color severity column red for "High"
                    if (hookData.section === 'body' && hookData.column.index === 2) {
                        const val = hookData.cell.raw;
                        if (val === 'High') {
                            hookData.cell.styles.textColor = [220, 38, 38];
                            hookData.cell.styles.fontStyle = 'bold';
                        } else if (val === 'Medium') {
                            hookData.cell.styles.textColor = [202, 138, 4];
                        }
                    }
                },
            });
            cursorY = doc.lastAutoTable.finalY + 12;

            // ── E. Topic Distribution Table ────────────────────────────
            const topics = data?.qualitative?.topic_distribution || [];
            if (topics.length > 0) {
                // Check if we need a new page
                if (cursorY > doc.internal.pageSize.getHeight() - 60) {
                    doc.addPage();
                    cursorY = 20;
                }

                doc.setFontSize(13);
                doc.setFont('helvetica', 'bold');
                doc.setTextColor(17, 24, 39);
                doc.text('AI Conversational Topic Distribution', margin, cursorY);
                cursorY += 6;

                autoTable(doc, {
                    startY: cursorY,
                    head: [['Topic', 'Volume %']],
                    body: topics.map(t => [t.topic || '—', `${t.percentage ?? 0}%`]),
                    theme: 'striped',
                    headStyles: { fillColor: [79, 70, 229], textColor: 255, fontStyle: 'bold', fontSize: 9 },
                    bodyStyles: { fontSize: 9, textColor: [31, 41, 55] },
                    alternateRowStyles: { fillColor: [238, 242, 255] },
                    margin: { left: margin, right: margin },
                    tableWidth: 120,
                });
                cursorY = doc.lastAutoTable.finalY + 12;
            }

            // ── F. Analyst Narrative — Lagging Alert ───────────────────
            const riskSummary = data?.qualitative?.lagging_developer?.risk_summary;
            if (riskSummary) {
                if (cursorY > doc.internal.pageSize.getHeight() - 50) {
                    doc.addPage();
                    cursorY = 20;
                }

                // Red alert header
                doc.setFillColor(254, 242, 242);
                doc.setDrawColor(220, 38, 38);
                doc.setLineWidth(0.3);
                const boxX = margin;
                const boxW = pageWidth - margin * 2;

                doc.setFontSize(12);
                doc.setFont('helvetica', 'bold');
                doc.setTextColor(153, 27, 27);
                doc.text('⚠  AI ANALYST NARRATIVE & ALERTS', margin, cursorY);
                cursorY += 6;

                // Risk summary box
                doc.setFontSize(9);
                doc.setFont('helvetica', 'normal');
                doc.setTextColor(55, 65, 81);
                const splitText = doc.splitTextToSize(riskSummary, boxW - 8);
                const boxH = splitText.length * 5 + 10;

                doc.roundedRect(boxX, cursorY, boxW, boxH, 2, 2, 'FD');
                doc.text(splitText, boxX + 4, cursorY + 7);
                cursorY += boxH + 10;
            }

            // ── Footer ────────────────────────────────────────────────
            const totalPages = doc.internal.getNumberOfPages();
            for (let i = 1; i <= totalPages; i++) {
                doc.setPage(i);
                doc.setFontSize(8);
                doc.setFont('helvetica', 'normal');
                doc.setTextColor(156, 163, 175);
                doc.text(
                    `O.N.E. Confidential — Page ${i} of ${totalPages}`,
                    pageWidth / 2,
                    doc.internal.pageSize.getHeight() - 8,
                    { align: 'center' }
                );
            }

            // ── G. Save ───────────────────────────────────────────────
            doc.save('ONE_Analytics_Report.pdf');
        } catch (err) {
            console.error('PDF export failed:', err);
            alert('PDF export failed. Please try again.');
        } finally {
            setIsExporting(false);
        }
    };

    useEffect(() => {
        const fetchAnalytics = async () => {
             try {
                 const token = sessionStorage.getItem('token');
                 const res = await axios.get('http://localhost:8000/api/v1/hr/analytics/deep-dive', {
                     headers: { Authorization: `Bearer ${token}` },
                     withCredentials: true
                 });
                 setData(res.data);
             } catch (err) {
                 console.error("Failed to load AI analytics payload", err);
                 setError("Failed to fetch analytics deep-dive data.");
             } finally {
                 setLoading(false);
             }
        };
        fetchAnalytics();
    }, []);

    // Combine for ScatterChart: Developer Proficiency Matrix
    const scatterData = [];
    if (data?.quantitative?.completion_matrix && data?.qualitative?.developer_insights) {
        data.quantitative.completion_matrix.forEach(comp => {
            const insight = data.qualitative.developer_insights.find(i => i.developer_id === comp.developer_id);
            if (insight) {
                scatterData.push({
                    name: comp.employee_name,
                    percent_complete: comp.percent_complete,
                    question_complexity_score: insight.question_complexity_score,
                    question_severity: insight.question_severity
                });
            }
        });
    }

    const COLORS = ['#1C1917', '#93C5FD', '#78716C', '#BFDBFE', '#A8A29E'];

    const getSeverityColor = (severity) => {
        if (severity === 'High') return '#e11d48';
        if (severity === 'Medium') return '#d97706';
        return '#059669';
    };

    return (
        <div className="min-h-screen bg-[#F7F5F0] text-stone-900 font-sans flex">
            {/* Sidebar */}
            <aside className="w-64 border-r border-stone-200 bg-[#F2F0EA] flex flex-col hidden md:flex flex-shrink-0">
                <div className="p-6 border-b border-stone-200">
                <div className="flex items-center gap-2.5 font-serif font-bold text-stone-900 text-lg tracking-tight">
                    <div className="w-7 h-7 rounded-sm bg-stone-900 flex items-center justify-center text-stone-100 font-mono text-xs">O</div>
                    O.N.E. <span className="font-sans text-xs uppercase font-mono tracking-widest text-stone-400">Admin</span>
                </div>
                </div>
                
                <nav className="flex-1 px-4 space-y-1 mt-6 text-xs font-medium">
                <Link to="/admin" className="px-3 py-2.5 rounded-sm text-stone-600 hover:text-stone-900 hover:bg-stone-200/60 transition-colors flex items-center gap-3">
                    <LayoutDashboard size={16} />
                    Dashboard
                </Link>
                <Link to="/admin/developers" className="px-3 py-2.5 rounded-sm text-stone-600 hover:text-stone-900 hover:bg-stone-200/60 transition-colors flex items-center gap-3">
                    <Users size={16} />
                    Developers
                </Link>
                <Link to="/admin/analytics" className="px-3 py-2.5 rounded-sm bg-stone-900 text-stone-100 flex items-center gap-3 shadow-sm cursor-pointer">
                    <BarChart2 size={16} />
                    Analytics
                </Link>
                </nav>

                <div className="p-4 border-t border-stone-200">
                <Link to="/admin/settings" className="flex items-center gap-3 px-2 py-2 rounded-sm hover:bg-stone-200/60 cursor-pointer transition-colors">
                    <div className="w-7 h-7 rounded-sm bg-stone-200 flex flex-shrink-0 items-center justify-center text-stone-800 text-xs font-mono font-bold border border-stone-300">
                        {adminProfile?.name ? adminProfile.name.split(' ').map(w => w[0]).join('').toUpperCase().slice(0, 2) : <UserIcon size={14} />}
                    </div>
                    <div className="flex-1 min-w-0">
                        <p className="text-xs font-semibold text-stone-900 truncate">{adminProfile?.name || 'Loading...'}</p>
                        <p className="text-[10px] text-stone-500 font-mono truncate capitalize">{adminProfile?.role?.replace('_', ' ') || '...'}</p>
                    </div>
                    <Settings size={14} className="text-stone-400" />
                </Link>
                </div>
            </aside>

            {/* Main Content */}
            <main className="flex-1 flex flex-col min-w-0 h-screen overflow-y-auto overflow-x-hidden">
                {/* Header */}
                <header className="px-8 py-6 flex flex-col md:flex-row md:justify-start items-center gap-4">
                    {/* Clean header */}
                </header>

                <div className="px-8 pb-12 w-full max-w-7xl mx-auto space-y-8">
                    {/* Header Title */}
                    <div>
                        <h1 className="text-2xl font-bold font-serif tracking-tight text-stone-900 mb-1">Analytics & AI Insights</h1>
                        <p className="text-xs font-mono uppercase tracking-widest text-stone-500">Qualitative and quantitative diagnostics powered by LLM.</p>
                    </div>

                    {loading ? (
                         <div className="w-full h-64 bg-white border border-stone-200 rounded-md shadow-sm flex flex-col items-center justify-center animate-pulse">
                              <div className="size-8 rounded-full border-2 border-stone-300 border-t-stone-900 animate-spin mb-3" />
                              <p className="text-xs font-mono uppercase tracking-widest text-stone-500">Processing Chat Transcripts & Aggregating Metrics...</p>
                         </div>
                    ) : error ? (
                        <div className="bg-rose-50 border border-rose-200 text-rose-800 p-4 rounded-sm text-xs font-mono flex items-center gap-3">
                            <AlertTriangle size={16} />
                            {error}
                        </div>
                    ) : (
                        <>
                            {/* AI Insights Alert Banner */}
                            {data?.qualitative?.lagging_developer && data.qualitative.lagging_developer.developer_id && (
                                <section className="bg-rose-50 border border-rose-200 rounded-md p-5 shadow-sm">
                                    <div className="flex items-start gap-4">
                                        <div className="w-8 h-8 rounded-sm bg-rose-100 flex items-center justify-center text-rose-800 flex-shrink-0 border border-rose-200">
                                            <AlertTriangle size={16} />
                                        </div>
                                        <div>
                                            <h3 className="text-rose-950 font-serif font-bold text-sm tracking-tight flex items-center gap-2">
                                                Intervention Required <span className="px-2 py-0.5 rounded-sm text-[9px] font-mono font-bold tracking-widest bg-rose-800 text-white uppercase">Critical</span>
                                            </h3>
                                            <p className="text-rose-800 text-xs mt-1 leading-relaxed">
                                                {data.qualitative.lagging_developer.risk_summary}
                                            </p>
                                        </div>
                                    </div>
                                </section>
                            )}

                            {/* Dense Visualization Grid */}
                            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                                
                                {/* Chart 1: Cohort Progress */}
                                <div className="bg-white border border-stone-200 rounded-md p-6 shadow-sm flex flex-col h-[380px]">
                                    <h3 className="text-stone-900 font-serif font-bold text-sm tracking-tight mb-6">Cohort Progress Tracker</h3>
                                    <div className="flex-1 w-full min-h-0">
                                        <ResponsiveContainer width="100%" height="100%">
                                            <BarChart data={data?.quantitative?.completion_matrix || []}>
                                                <CartesianGrid strokeDasharray="3 3" stroke="#F5F5F4" vertical={false} />
                                                <XAxis dataKey="employee_name" stroke="#78716C" tick={{fill: '#78716C', fontSize: 11}} tickLine={false} axisLine={false} />
                                                <YAxis stroke="#78716C" tick={{fill: '#78716C', fontSize: 11}} tickLine={false} axisLine={false} domain={[0, 100]} />
                                                <Tooltip 
                                                    cursor={{fill: '#F7F5F0'}}
                                                    contentStyle={{backgroundColor: '#FFFFFF', borderColor: '#E7E5E4', color: '#1C1917', borderRadius: '4px', boxShadow: '0 2px 8px rgba(0,0,0,0.05)', fontSize: '12px'}}
                                                    itemStyle={{color: '#1C1917', fontWeight: 'bold'}}
                                                />
                                                <Bar dataKey="percent_complete" fill="#1C1917" radius={[2, 2, 0, 0]} maxBarSize={36} />
                                            </BarChart>
                                        </ResponsiveContainer>
                                    </div>
                                </div>

                                {/* Chart 2: Task Velocity */}
                                <div className="bg-white border border-stone-200 rounded-md p-6 shadow-sm flex flex-col h-[380px]">
                                    <h3 className="text-stone-900 font-serif font-bold text-sm tracking-tight mb-6">Task Velocity (Avg Hours)</h3>
                                    <div className="flex-1 w-full min-h-0">
                                        <ResponsiveContainer width="100%" height="100%">
                                            <AreaChart data={data?.quantitative?.task_velocity || []}>
                                                <defs>
                                                    <linearGradient id="colorVelocity" x1="0" y1="0" x2="0" y2="1">
                                                        <stop offset="5%" stopColor="#BFDBFE" stopOpacity={0.6}/>
                                                        <stop offset="95%" stopColor="#BFDBFE" stopOpacity={0}/>
                                                    </linearGradient>
                                                </defs>
                                                <CartesianGrid strokeDasharray="3 3" stroke="#F5F5F4" vertical={false} />
                                                <XAxis dataKey="title" stroke="#78716C" tick={{fill: '#78716C', fontSize: 10}} tickLine={false} axisLine={false} tickFormatter={(val) => val.length > 15 ? val.substring(0, 15) + '...' : val} />
                                                <YAxis stroke="#78716C" tick={{fill: '#78716C', fontSize: 11}} tickLine={false} axisLine={false} />
                                                <Tooltip 
                                                    contentStyle={{backgroundColor: '#FFFFFF', borderColor: '#E7E5E4', color: '#1C1917', borderRadius: '4px', boxShadow: '0 2px 8px rgba(0,0,0,0.05)', fontSize: '12px'}}
                                                />
                                                <Area type="monotone" dataKey="avg_duration_hours" stroke="#1E40AF" strokeWidth={2} fillOpacity={1} fill="url(#colorVelocity)" />
                                            </AreaChart>
                                        </ResponsiveContainer>
                                    </div>
                                </div>

                                {/* Chart 3: Topic Distribution */}
                                <div className="bg-white border border-stone-200 rounded-md p-6 shadow-sm flex flex-col h-[380px]">
                                    <h3 className="text-stone-900 font-serif font-bold text-sm tracking-tight mb-6">AI Conversational Topic Distribution</h3>
                                    <div className="flex-1 w-full min-h-0 relative">
                                        <ResponsiveContainer width="100%" height="100%">
                                            <PieChart>
                                                <Pie
                                                    data={data?.qualitative?.topic_distribution || []}
                                                    dataKey="percentage"
                                                    nameKey="topic"
                                                    cx="50%"
                                                    cy="50%"
                                                    innerRadius={70}
                                                    outerRadius={100}
                                                    stroke="none"
                                                    paddingAngle={4}
                                                >
                                                    {(data?.qualitative?.topic_distribution || []).map((entry, index) => (
                                                        <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                                                    ))}
                                                </Pie>
                                                <Tooltip 
                                                    contentStyle={{backgroundColor: '#FFFFFF', borderColor: '#E7E5E4', color: '#1C1917', borderRadius: '4px', boxShadow: '0 2px 8px rgba(0,0,0,0.05)', fontSize: '12px'}}
                                                    formatter={(value) => `${value}%`}
                                                />
                                            </PieChart>
                                        </ResponsiveContainer>
                                        <div className="absolute inset-0 flex flex-col items-center justify-center pointer-events-none">
                                            <span className="text-xl font-bold font-serif text-stone-900 tracking-tight">100%</span>
                                            <span className="text-[9px] uppercase font-mono tracking-widest text-stone-400 font-semibold">Topics</span>
                                        </div>
                                    </div>
                                </div>

                                {/* Chart 4: Proficiency Matrix */}
                                <div className="bg-white border border-stone-200 rounded-md p-6 shadow-sm flex flex-col h-[380px]">
                                    <h3 className="text-stone-900 font-serif font-bold text-sm tracking-tight mb-6">Developer Proficiency Matrix</h3>
                                    <div className="flex-1 w-full min-h-0">
                                        <ResponsiveContainer width="100%" height="100%">
                                            <ScatterChart margin={{ top: 10, right: 10, bottom: 10, left: 10 }}>
                                                <CartesianGrid strokeDasharray="3 3" stroke="#F5F5F4" />
                                                <XAxis type="number" dataKey="percent_complete" name="Progression" unit="%" stroke="#78716C" tick={{fill: '#78716C', fontSize: 11}} domain={[0, 100]} />
                                                <YAxis type="number" dataKey="question_complexity_score" name="Complexity Score" stroke="#78716C" tick={{fill: '#78716C', fontSize: 11}} domain={[1, 10]} />
                                                <ZAxis type="category" dataKey="name" name="Developer" />
                                                <Tooltip 
                                                    cursor={{strokeDasharray: '3 3', stroke: '#E7E5E4'}}
                                                    contentStyle={{backgroundColor: '#FFFFFF', borderColor: '#E7E5E4', color: '#1C1917', borderRadius: '4px', boxShadow: '0 2px 8px rgba(0,0,0,0.05)', fontSize: '12px'}}
                                                />
                                                <Scatter name="Developers" data={scatterData}>
                                                    {
                                                        scatterData.map((entry, index) => (
                                                            <Cell key={`cell-${index}`} fill={getSeverityColor(entry.question_severity)} />
                                                        ))
                                                    }
                                                </Scatter>
                                            </ScatterChart>
                                        </ResponsiveContainer>
                                        <div className="flex justify-center gap-6 mt-2">
                                            <div className="flex items-center gap-1.5"><div className="w-2.5 h-2.5 rounded-full bg-rose-600"></div><span className="text-[10px] uppercase font-mono text-stone-500">High</span></div>
                                            <div className="flex items-center gap-1.5"><div className="w-2.5 h-2.5 rounded-full bg-amber-600"></div><span className="text-[10px] uppercase font-mono text-stone-500">Med</span></div>
                                            <div className="flex items-center gap-1.5"><div className="w-2.5 h-2.5 rounded-full bg-emerald-600"></div><span className="text-[10px] uppercase font-mono text-stone-500">Low</span></div>
                                        </div>
                                    </div>
                                </div>

                                {/* Chart 5: Developer Frustration Index */}
                                <div className="bg-white border border-stone-200 rounded-md p-6 shadow-sm flex flex-col h-[380px]">
                                    <h3 className="text-stone-900 font-serif font-bold text-sm tracking-tight mb-6">Developer Frustration Index</h3>
                                    <div className="flex-1 w-full min-h-0">
                                        <ResponsiveContainer width="100%" height="100%">
                                            <BarChart data={data?.qualitative?.sentiment_index || []}>
                                                <CartesianGrid strokeDasharray="3 3" stroke="#F5F5F4" vertical={false} />
                                                <XAxis dataKey="employee_name" stroke="#78716C" tick={{fill: '#78716C', fontSize: 11}} tickLine={false} axisLine={false} />
                                                <YAxis stroke="#78716C" tick={{fill: '#78716C', fontSize: 11}} tickLine={false} axisLine={false} domain={[0, 100]} />
                                                <Tooltip 
                                                    cursor={{fill: '#F7F5F0'}}
                                                    contentStyle={{backgroundColor: '#FFFFFF', borderColor: '#E7E5E4', color: '#1C1917', borderRadius: '4px', boxShadow: '0 2px 8px rgba(0,0,0,0.05)', fontSize: '12px'}}
                                                    formatter={(value, name, props) => {
                                                        const emotion = props.payload.primary_emotion || 'Unknown';
                                                        return [`${value} (${emotion})`, 'Frustration Level'];
                                                    }}
                                                />
                                                <Bar dataKey="frustration_score" radius={[2, 2, 0, 0]} maxBarSize={36}>
                                                    {(data?.qualitative?.sentiment_index || []).map((entry, index) => {
                                                        let color = '#1C1917';
                                                        if (entry.frustration_score > 70) color = '#e11d48';
                                                        if (entry.frustration_score < 30) color = '#059669';
                                                        return <Cell key={`cell-${index}`} fill={color} />;
                                                    })}
                                                </Bar>
                                            </BarChart>
                                        </ResponsiveContainer>
                                    </div>
                                </div>

                                {/* Chart 6: Autonomy vs AI Reliance */}
                                <div className="bg-white border border-stone-200 rounded-md p-6 shadow-sm flex flex-col h-[380px]">
                                    <h3 className="text-stone-900 font-serif font-bold text-sm tracking-tight mb-6">Autonomy vs. AI Reliance</h3>
                                    <div className="flex-1 w-full min-h-0">
                                        <ResponsiveContainer width="100%" height="100%">
                                            <RadarChart cx="50%" cy="50%" outerRadius="65%" data={data?.qualitative?.autonomy_scores || []}>
                                                <PolarGrid stroke="#E7E5E4" />
                                                <PolarAngleAxis dataKey="employee_name" tick={{ fill: '#78716C', fontSize: 11 }} />
                                                <PolarRadiusAxis angle={30} domain={[0, 10]} tick={{ fill: '#78716C', fontSize: 10 }} axisLine={false} tickLine={false} />
                                                <Tooltip 
                                                    contentStyle={{backgroundColor: '#FFFFFF', borderColor: '#E7E5E4', color: '#1C1917', borderRadius: '4px', boxShadow: '0 2px 8px rgba(0,0,0,0.05)', fontSize: '12px'}}
                                                />
                                                <Radar name="Independence Rating" dataKey="independence_rating" stroke="#1E40AF" fill="#BFDBFE" fillOpacity={0.4} strokeWidth={2} />
                                            </RadarChart>
                                        </ResponsiveContainer>
                                    </div>
                                </div>

                            </div>
                        </>
                    )}
                </div>
            </main>
        </div>
    );
};
