from enum import Enum

class FSMState(str, Enum):
    WELCOME = "WELCOME"
    PROFILING = "PROFILING"
    PLAN_GENERATION = "PLAN_GENERATION"
    ONBOARDING_EXECUTION = "ONBOARDING_EXECUTION"
    CHECKLIST_REVIEW = "CHECKLIST_REVIEW"
    COMPLETED = "COMPLETED"
    FREE_QA = "FREE_QA"   # overlay state — doesn't replace current state

# Valid transitions: {current_state: [allowed_next_states]}
VALID_TRANSITIONS = {
    FSMState.WELCOME: [FSMState.PROFILING],
    FSMState.PROFILING: [FSMState.PLAN_GENERATION],
    FSMState.PLAN_GENERATION: [FSMState.ONBOARDING_EXECUTION],
    FSMState.ONBOARDING_EXECUTION: [FSMState.CHECKLIST_REVIEW, FSMState.FREE_QA],
    FSMState.CHECKLIST_REVIEW: [FSMState.COMPLETED, FSMState.ONBOARDING_EXECUTION],
    FSMState.COMPLETED: [],
    FSMState.FREE_QA: [FSMState.ONBOARDING_EXECUTION, FSMState.CHECKLIST_REVIEW],
}
